// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "myceactivex.h"

/////////////////////////////////////////////////////////////////////////////
// CMyCEActiveX

IMPLEMENT_DYNCREATE(CMyCEActiveX, CWnd)

CString CMyCEActiveX::GetMsgContext()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CMyCEActiveX::SetMsgContext(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CMyCEActiveX operations

void CMyCEActiveX::ShowMessage()
{
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMyCEActiveX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
