<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: IPC_MSGCLIENT - Win32 (WCE x86) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\wangbing\LOCALS~1\Temp\RSP4A.tmp" with contents
[
/nologo /base:"0x00010000" /stack:0x10000,0x1000 /entry:"wWinMainCRTStartup" /incremental:yes /pdb:"X86Dbg/IPC_MSGCLIENT1.pdb" /debug /out:"X86Dbg/IPC_MSGCLIENT1.exe" /subsystem:windowsce,3.00 /MACHINE:IX86 
".\X86Dbg\IPC_MSGCLIENT.obj"
".\X86Dbg\IPC_MSGCLIENTDlg.obj"
".\X86Dbg\IPCClient.obj"
".\X86Dbg\StdAfx.obj"
".\X86Dbg\IPC_MSGCLIENT.res"
]
Creating command line "link.exe @C:\DOCUME~1\wangbing\LOCALS~1\Temp\RSP4A.tmp"
<h3>Output Window</h3>
Linking...




<h3>Results</h3>
IPC_MSGCLIENT1.exe - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
